//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenPseudonymiser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OpenPResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenPResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenPseudonymiser.OpenPResources", typeof(OpenPResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string AllowExport {
            get {
                return ResourceManager.GetString("AllowExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ribble.
        /// </summary>
        internal static string DefaultSalt {
            get {
                return ResourceManager.GetString("DefaultSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your data has an NHS number field you can select this from the drop down. This will enable NHS number validation on the data.
        ///
        ///Tick the column(s) you want to use for the Digest and untick any columns that you don&apos;t want to see on the Output.
        ///
        ///You can also pick &quot;process as date&quot; to have the software flatten dates for you &quot;i.e. round them down to 1/1/yyyy&quot; OpenPseudonymiser supports the following date formats: &quot;yyyyMMdd&quot;, &quot;dd/MM/yy&quot;, &quot;dd/MM/yyyy&quot;, &quot;dd.MM.yy&quot;, &quot;dd.MM.yyyy&quot;.
        /// </summary>
        internal static string HelpText_Columns {
            get {
                return ResourceManager.GetString("HelpText_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- OpenPseudonymiser version 2.0.2 --
        ///
        ///OpenPseudonymiser batch processor is a standalone program developed by Julia Hippisley-Cox from the University of Nottingham
        ///
        ///The program can process Comma Seperated Files (CSVs) and replace identifyable data with an pseudonymised code called the &apos;Digest&apos; using a one way irreversible hashing algorithm
        ///
        ///-          For further information see www.openpseudonymiser.org
        ///-          Bugs should be reported to support@openpseudonymiser.org
        ///
        ///This help window has diffe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText_General {
            get {
                return ResourceManager.GetString("HelpText_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt is required to create the digests. Salt can be created using the OpenP website:
        ///www.openpseudonymiser.org
        ///
        ///The address for the OpenP Key server is:
        ///
        ///https://keyserverapi.openpseudonymiser.org/api/.
        /// </summary>
        internal static string HelpText_Salt {
            get {
                return ResourceManager.GetString("HelpText_Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you press finish OpenPseudonymiser will create two files:
        ///
        ///1. The ‘RunLog’. 
        ///A text file with some metadata about the process including the results of any NHS number validation. This will have the same name as your input file, but will have a file extension of “OpenPseudonymiserRunLog”
        ///
        ///
        ///2. The processed CSV file
        ///This will have the same name as your input file but with the word “OpenPseudonymised_” before it..
        /// </summary>
        internal static string HelpText_Target {
            get {
                return ResourceManager.GetString("HelpText_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Julia Hippisley-Cox, University of Nottingham 2011
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Publ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenceText {
            get {
                return ResourceManager.GetString("LicenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB,DateOfBirth,DOD,DateOfDeath,TransferDate.
        /// </summary>
        internal static string PreConfig_DateCols {
            get {
                return ResourceManager.GetString("PreConfig_DateCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHSNumber.
        /// </summary>
        internal static string PreConfig_DigestCols {
            get {
                return ResourceManager.GetString("PreConfig_DigestCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all except:NHSNumber.
        /// </summary>
        internal static string PreConfig_OutputCols {
            get {
                return ResourceManager.GetString("PreConfig_OutputCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example A - Sep 2011.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encryptedfile.
        /// </summary>
        internal static string SaltMode {
            get {
                return ResourceManager.GetString("SaltMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFG.
        /// </summary>
        internal static string SettingsHash {
            get {
                return ResourceManager.GetString("SettingsHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string UsePreconfigSettings {
            get {
                return ResourceManager.GetString("UsePreconfigSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string UseSettingsFile {
            get {
                return ResourceManager.GetString("UseSettingsFile", resourceCulture);
            }
        }
    }
}
